/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gabia.devmcp

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppTest {
    @Test
    fun basicTest() {
        // 기본 테스트
        assertNotNull("test", "basic test should pass")
    }
}
